pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        sh '''mkdir folder1
cd folder1 
touch text1.txt text2.txt text3.txt text4.txt
ls
'''
      }
    }
  }
}
